apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubeflow-helm-chart.fullname" . }}
  labels:
    app: {{ include "kubeflow-helm-chart.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "kubeflow-helm-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "kubeflow-helm-chart.name" . }}
    spec:
      containers:
        - name: {{ include "kubeflow-helm-chart.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          env:
            - name: ENV_VAR_NAME
              value: {{ .Values.envVarName | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}