apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeflow-helm-chart.fullname" . }}
  labels:
    {{- include "kubeflow-helm-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    app: {{ include "kubeflow-helm-chart.name" . }}
    release: {{ .Release.Name }}